version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo "Enter prebuild phase"
  build:
    commands:
      - echo "Enter build phase 01"
      - echo $CODEBUILD_SRC_DIR
      - cd $CODEBUILD_SRC_DIR/restful-booker
      - pwd
      - npm install
  post_build:
    commands:
      - echo  "Enter post build phase 02."

artifacts:
  base-directory: ./restful-booker/
  files:
    - '**/*'
