version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo "Enter prebuild phase"
  build:
    commands:
      - echo "Enter build phase 01"
      - echo $CODEBUILD_SRC_DIR
      - ls $CODEBUILD_SRC_DIR
      - npm install
  post_build:
    commands:
      - echo  "Enter post build phase 02."

artifacts:
  base-directory: ./restul-bookder/
  files:
    - '**/*'
