version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo "Enter prebuild phase"
      - npm install
  build:
    commands:
      - echo "Enter build phase 01"
  post_build:
    commands:
      - echo  "Enter post build phase 02."

artifacts:
  files:
    - restful-booker/**/*
