version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Enter prebuild phase"
  build:
    commands:
      - echo "Enter build phase test"
      - echo $CODEBUILD_SRC_DIR
      - ls $CODEBUILD_SRC_DIR
      - chmod -R 755 .
      - mvn clean test
      - echo Build completed tests on `date`

  post_build:
    commands:
      - echo  "Enter post build phase 02."
artifacts:
  files:
    - '**/*'
reports:
  SurefireReports:
  files:
    - '**/*'
  base-directory: 'target/surefire-reports'


