version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Enter prebuild phase"
  build:
    commands:
      - echo "Enter build phase test"
      - echo $CODEBUILD_SRC_DIR
      - cd $CODEBUILD_SRC_DIR/QA-MeetUp-API-Workshop
      - chmod -R 755 .
      - mvn clean test
      - echo Build completed tests on `date`

  post_build:
    commands:
      - echo  "Enter post build phase 02."
artifacts:
  files:
    - '**/*'
  base-directory: QA-MeetUp-API-Workshop

SurefireReports:
  files:
    - '**/*'
  base-directory: 'QA-MeetUp-API-Workshop/target/surefire-reports'

